### ISSUE TITLE
I need opore unit research in v6

### ISSUE THREAD

**Issue by EpicCionLion** [xamionex/Opore-Mod#11]
**Describe the bug**
No unit research on campaign
**To Reproduce**
1. Opore unit factory researched
2. Look at factory information
3. Seen no unit can't be make

**Expected behavior**
I want to make some opore unit to have fun in campaign, turn out I can't

**Screenshots**

**Desktop (please complete the following information if you think its relevant, I don't actually need this):**
 - phone user

**Smartphone (please complete the following information if you think its relevant, I don't actually need this):**
 - no need it is

**Additional context**
That all, just add so I can research opore unit and have fun in v6 campaign
 
![Screenshot_20210120-000050_Mindustry](https://user-images.githubusercontent.com/77688176/105067877-c6bebe80-5ab2-11eb-9899-579e103a6779.jpg)

**Comment by xamionex** [comment]
You are supposed to use the constructor and not the reconstructors to make units, the reconstructors are to upgrade them.

**Comment by EpicCionLion** [comment]
![Screenshot_20210120-000024_Mindustry](https://user-images.githubusercontent.com/77688176/105171737-28356a80-5b51-11eb-8982-5331922d8d46.jpg)
I mean this. It didn't have an output

**Comment by xamionex** [comment]
Check what version of the mod you're on, if it's v67 that's a bug and i'll check it out when i can

**Comment by xamionex** [comment]
if it's under v67, update your version

**Comment by xamionex** [comment]
I tested on my phone and pc, both work and the phone is using the public version. You probably have an outdated version, update ingame by importing from github with `xamionex/opore-mod`

**Comment by xamionex** [comment]
No response, assuming fixed. Open again if not.
