### ISSUE TITLE
The frazzure is not uncked and I already prodused some

### ISSUE THREAD

**Issue by Joachim-barre** [xamionex/Opore-Mod#13]
**Describe the bug**
The resherch show that I have to unlock frazzure

**Screenshots**
![Screenshot_20220609-193312.png](https://user-images.githubusercontent.com/104816842/172908974-189dd2e9-a34a-468a-81f2-a4a634b29005.png)

**Desktop :**
 - androide
 - mod : 69 game : 246
- ulephone armor X8

**Comment by CSyoey** [comment]
You can edit the .json file to remove Frazzure as a requirement

**Comment by Joachim-barre** [comment]
Thanks

**Comment by Joachim-barre** [comment]
Just I'm new and I don't now if I have to close

**Comment by Joachim-barre** [comment]
I was just that the frazzure ore as the same name as the liquide
