### ISSUE TITLE
Yo things are still present from the halowenn update

### ISSUE THREAD

**Issue by CA6** [xamionex/Opore-Mod#3]
Ok so the unit and mech "are still present" they exist I don't know if you're planning dom thing with them but they exist in the data base.. just an fyi

**Comment by xamionex** [comment]
Thanks for reporting just please *use my github email address next
time* (*amioneatgithub@gmail.com
<amioneatgithub@gmail.com>*)

**Comment by xamionex** [comment]
Disregard my comment, i'm going to use github, keep reporting in the Issues tab if you found a bug
