### ISSUE TITLE
Just a picture of a map i made

### ISSUE THREAD

**Issue by gavinknapp17** [xamionex/Opore-Mod#8]
Well it's not a request but I have a map, and I'm giving credit to the people who made opore pvp defense or whatever it's called. My map is called smaller opore pvp defense map.
![map_29](https://user-images.githubusercontent.com/65633499/82390255-3ce2c100-9a0c-11ea-983a-58ee106c4d77.png)

**Comment by xamionex** [comment]
Don't tell me that you credited my mod in your map, just add it in the description of your map and that's all. You don't need to credit people like this but i appreciate it. Have fun!
