### ISSUE TITLE
Azurite vault is buggy in V6

### ISSUE THREAD

**Issue by keittehvan** [xamionex/Opore-Mod#9]
**Describe the bug**
Azurite vault breaks after building in V6
You can not deconstruct it
You can not use the space it is placed in
Every time you restart the game, the vault takes more space

Did not try other vaults

**To Reproduce**
Just build the vault

**Expected behavior**
The vault would work like a normal vault

**Screenshots**
![azurite_vault_buggy](https://user-images.githubusercontent.com/13797260/101289340-7e01bd80-3804-11eb-895b-acadaf866cc7.png)

**Desktop (please complete the following information if you think its relevant, I don't actually need this):**
 - OS: Windows

**Comment by keittehvan** [comment]
Changing the type from "Vault" to "StorageBlock" in the json ( https://github.com/xamionex/Opore-Mod/blob/master/content/blocks/storage/azurite-vault.json ) seems to fix this

**Comment by xamionex** [comment]
I'm sorry for not seeing this in the final build, i'll release a hotfix in a bit. Thank you!
